version: 2.1

orbs:
  eslint: arrai/eslint@2.0.1

jobs:

  run_tests:
    docker:
        - image: circleci/node:current
      # - image: cimg/ruby:2.7.1-node

    steps:
      - checkout
      - run: npm install --save
      - run: npm run test

workflows:
  lint_and_test:
    jobs:
      - eslint/eslint
      - run_tests



