version: 2.1
orbs:
  estlint:
jobs:
  run_tests:
    docker:
      - image: circleci/node10
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: npm install --save
      - run: npm run test

workflows:
  test:
    jobs:
      - run_tests
