version: 2.1

orbs:
  eslint: arrai/eslint@2.0.1

jobs:

  lint_and_test:
    docker:
      - image: cimg/ruby:2.7.1-node

    steps:
      - checkout
      - run: npm install --save
      - run: npm run lint

workflows:
  lint_and_test:
    jobs:
      - lint_and_test


