version: 2.1

jobs:
  run_tests:
    docker:
      - image: cimg/base:2020.01

    steps:
      - checkout
      - run: npm install --save
      - run: npm run test

workflows:
  test:
    jobs:
      - run_tests

